### PR TITLE
add review dto

### PR DESCRIPTION
**Pull request by Run37927**
- add review dto
- create route's Body now using CreateReviewDto type
- installed class validator and class transformer
- enable global validation pipe in main.ts
- link to [issue](https://github.com/RateTheLandlord/RateTheLandlord/issues/343)

for FE validation
`{
  "statusCode": 400,
  "message": [
    {
      "property": "landlord",
      "constraints": {
        "isNotEmpty": "landlord should not be empty",
        "isString": "landlord must be a string"
      }
    },
    {
      "property": "city",
      "constraints": {
        "isNotEmpty": "city should not be empty",
        "isString": "city must be a string"
      }
    }
  ],
  "error": "Bad Request"
}
`
This response can be parsed on the client side to display appropriate error messages to the user.

### CODE REVIEW

**Comment by kellenwiltshire** [comment]
I played around with this a bit this morning. Couldn't get it to function. I think something like this:

```await validate(review).then((errors) => {
      console.log(errors);
      return this.handleException(errors);
    });```

needs to be added to the `review.controller` for creating a review so that it tests the input. Maybe that helps you a bit. This is a lot more complicated of a solution that I was expecting, which is likely a good call and we can build on it easier for the future.

**Comment by Run37927** [comment]
image

**Comment by kellenwiltshire** [comment]
Okay, this is looking pretty good now! 

Unfortunately I am about to make it harder.

So, right now the file `review-data-layer.ts` does some checking for string length on different components (landlord name, city name and zip), lets move these checks into the DTO as well (`@MaxLength`) to clean them up.

Also, I noticed that if I pass an empty string with length `"   "`, that the check fails. The Review isn't entered into the system which is good, but there is not reason returned to the FE, just a 500 error.

Finally, Can you checkout the other open PR to see how they are displaying this information to the frontend with their validation and make sure that if the BE returns an error (landlord name can't be empty) that the frontend can handle this response (though, it shouldn't get past FE validation but it is good practice to have it)

**Comment by Run37927** [comment]
- merge develop in
- data transforming in dto
-

**Review by kellenwiltshire — APPROVED** [review]
Looks awesome!

**Pull request merged**
