### PR TITLE
#226

### PR DESCRIPTION
**Pull request by stephenmartin2951**
Modified filter selection to utilize virtualization. I don't have the all the reviews available locally so it is hard to gauge performance boost. Also, I had to add an additional dependency which could create stability concerns.

### CODE REVIEW

**Comment by RateTheLandlordAdmin** [comment]
Hey @stephenmartin2951, I just pushed a changed to develop/main changing the listboxes to comboboxes for easier navigating. I like the idea of virtualisation though if you could amend this to work with them?

**Comment by stephenmartin2951** [comment]
Adjusted the virtualization for the comboboxes. Interested to know if it works any better!

**Comment by RateTheLandlordAdmin** [comment]
This looks great and seems to function well in my testing. 

Can you look at the workflow checks that have failed? If you need a hand, let me know

**Comment by stephenmartin2951** [comment]
I'm out of town for the next week but I will take a look once I return!

**Comment by stephenmartin2951** [comment]
Weird error on the docker-build test. The command runs fine locally using the variables.

**Comment by RateTheLandlordAdmin** [comment]
Yes that is an issue I am working on. Hopefully have a fix soon.

Will take a look at this tonight and get it merged!

**Review by RateTheLandlordAdmin — APPROVED** [review]
LGTM!

**Review by RateTheLandlordAdmin — APPROVED** [review]

**Pull request merged**
