### PR TITLE
Page framework

### PR DESCRIPTION
**Pull request by kellenwiltshire**
General framework completed for the initial pages and components. Ready to be filled in once designs completed.

### CODE REVIEW

**Comment by kellenwiltshire** [comment]
Once merged the branch can be deleted.

**Comment by zeshan321** [comment]
Can we change the file and folder names to be lowercase for consistency?

**Comment by kellenwiltshire** [comment]
I can see changing the folder names to lower case but I believe it is React convention for jsx/tsx files to be in PascalCase with capital letters.

The exception for this would be the pages as they will appear in the url.

I'm good either way, just making sure there's consistency in both our project but also between React projects.

**Comment by zeshan321** [comment]
React doesn't have a specific convention. There are companies and projects that have their own style guides. Currently in the frontend folder we have kebab and pascal case. We should pick one here, I typically prefer kebab case but open to others.

**Comment by kellenwiltshire** [comment]
Yes, that part I know for sure!

Should be all fixed up now!

**Comment by kellenwiltshire** [comment]
Finally fixed it. All the cases should be kebab-case now!

**Review by zeshan321 — APPROVED** [review]

**Pull request merged**
