### PR TITLE
reduce button text font & increase country section margin top

### PR DESCRIPTION
**Pull request by Run37927**
link to issue: https://github.com/RateTheLandlord/RateTheLandlord/issues/188

### CODE REVIEW

**Comment by Run37927** [comment]
@RateTheLandlordAdmin , could you please review my Pull Request? Thanks!

**Review by RateTheLandlordAdmin — APPROVED** [review]

**Comment by RateTheLandlordAdmin** [comment]
@Run37927 This keeps failing the build. Please check.

**Comment by Run37927** [comment]
> @Run37927 This keeps failing the build. Please check.
looks like env vars not being setup correclty, will take a look now

**Comment by Run37927** [comment]
> @Run37927 This keeps failing the build. Please check.



> > @Run37927 This keeps failing the build. Please check.
> > looks like env vars not being setup correclty, will take a look now

the build is complaining about incorrect values for the frontend and backend ports, and those ports are set by environment variables which only the admin (and their private collaborators) can configure, do you mind take a quick look plz? thanks!!

**Pull request closed without merging**
