### PR TITLE
#8: Reviews page

### PR DESCRIPTION
**Pull request by kellenwiltshire**
Reviews page completed

### CODE REVIEW

**Comment by zeshan321** [comment]
Looks like linting is failing

**Comment by kellenwiltshire** [comment]
@zeshan321 Strange. I will take a look.

I will also update it with main/localization so it'll be more up-to-date overall.

**Comment by kellenwiltshire** [comment]
@zeshan321 Linting errors show as fixed on my computer now. Should be good to go?

**Comment by kellenwiltshire** [comment]
Now ready for Merge.

**Comment by zeshan321** [comment]
Looks good for now. We'd want to move the filtering to the backend eventually

**Review by zeshan321 — APPROVED** [review]

**Pull request merged**
