### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by kellenwiltshire**
Added Localization checks and supports in Next.Config. There is a check for current Locale now in _app.tsx as well.

Middleware was added for future support of locale switching.

https://nextjs.org/docs/advanced-features/i18n-routing

### CODE REVIEW

**Comment by zeshan321** [comment]
Can we migrate the existing hardcoded strings in the frontend to use localization?

**Comment by kellenwiltshire** [comment]
> Can we migrate the existing hardcoded strings in the frontend to use localization?

Yes, we should be able to do that I think. I will work on that and re-submit

**Comment by kellenwiltshire** [comment]
Got the localization working, but getting linting errors. Will hopefully fix them soon but as far as the docs go for Next-Intl they shouldn't be happening...

**Comment by kellenwiltshire** [comment]
https://next-intl-docs.vercel.app/

**Pull request closed without merging**
